const days = [
  {
    datetime: '2024-04-26',
    datetimeEpoch: 1714086000,
    tempmax: 51.7,
    tempmin: 40.6,
    temp: 46.7,
    feelslikemax: 51.7,
    feelslikemin: 36.9,
    feelslike: 43.3,
    dew: 42,
    humidity: 84.1,
    precip: 0.162,
    precipprob: 100,
    precipcover: 33.33,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 20.8,
    windspeed: 17.4,
    winddir: 80.4,
    pressure: 1002.8,
    cloudcover: 74.7,
    visibility: 8.9,
    solarradiation: 100.7,
    solarenergy: 8.9,
    uvindex: 4,
    severerisk: 10,
    sunrise: '05:43:07',
    sunriseEpoch: 1714106587,
    sunset: '20:14:34',
    sunsetEpoch: 1714158874,
    moonphase: 0.59,
    conditions: 'Rain, Partially cloudy',
    description: 'Partly cloudy throughout the day with rain clearing later.',
    icon: 'rain',
    stations: ['EGKK', 'EGKA', 'E8153', 'EGVO', 'EGLF'],
    source: 'comb',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    datetime: '2024-04-27',
    datetimeEpoch: 1714172400,
    tempmax: 52.6,
    tempmin: 47.7,
    temp: 50.7,
    feelslikemax: 52.6,
    feelslikemin: 42.5,
    feelslike: 50.1,
    dew: 46.5,
    humidity: 85.4,
    precip: 0.596,
    precipprob: 83.9,
    precipcover: 62.5,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 23,
    windspeed: 19.5,
    winddir: 99.4,
    pressure: 1001.3,
    cloudcover: 95.8,
    visibility: 12,
    solarradiation: 138.8,
    solarenergy: 12,
    uvindex: 6,
    severerisk: 10,
    sunrise: '05:41:13',
    sunriseEpoch: 1714192873,
    sunset: '20:16:10',
    sunsetEpoch: 1714245370,
    moonphase: 0.62,
    conditions: 'Rain, Overcast',
    description: 'Cloudy skies throughout the day with a chance of rain.',
    icon: 'rain',
    stations: null,
    source: 'fcst',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    datetime: '2024-04-28',
    datetimeEpoch: 1714258800,
    tempmax: 51,
    tempmin: 46.3,
    temp: 49,
    feelslikemax: 51,
    feelslikemin: 38.8,
    feelslike: 44.6,
    dew: 43.4,
    humidity: 81.1,
    precip: 0.295,
    precipprob: 93.5,
    precipcover: 41.67,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 25.9,
    windspeed: 21.9,
    winddir: 335.7,
    pressure: 1004.8,
    cloudcover: 81.3,
    visibility: 14.5,
    solarradiation: 146.6,
    solarenergy: 12.7,
    uvindex: 8,
    severerisk: 10,
    sunrise: '05:39:19',
    sunriseEpoch: 1714279159,
    sunset: '20:17:46',
    sunsetEpoch: 1714331866,
    moonphase: 0.66,
    conditions: 'Rain, Partially cloudy',
    description:
      'Partly cloudy throughout the day with a chance of rain throughout the day.',
    icon: 'rain',
    stations: null,
    source: 'fcst',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    datetime: '2024-04-29',
    datetimeEpoch: 1714345200,
    tempmax: 53.3,
    tempmin: 50.6,
    temp: 51.7,
    feelslikemax: 53.3,
    feelslikemin: 50.6,
    feelslike: 51.7,
    dew: 44.7,
    humidity: 76.8,
    precip: 0,
    precipprob: 9.7,
    precipcover: 0,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 17.4,
    windspeed: 13.4,
    winddir: 172.9,
    pressure: 1014.8,
    cloudcover: 23.9,
    visibility: 15,
    solarradiation: 295.1,
    solarenergy: 25.5,
    uvindex: 8,
    severerisk: 10,
    sunrise: '05:37:27',
    sunriseEpoch: 1714365447,
    sunset: '20:19:22',
    sunsetEpoch: 1714418362,
    moonphase: 0.69,
    conditions: 'Partially cloudy',
    description: 'Partly cloudy throughout the day.',
    icon: 'partly-cloudy-day',
    stations: null,
    source: 'fcst',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    datetime: '2024-04-30',
    datetimeEpoch: 1714431600,
    tempmax: 56.7,
    tempmin: 53.5,
    temp: 54.6,
    feelslikemax: 56.7,
    feelslikemin: 53.5,
    feelslike: 54.6,
    dew: 49.7,
    humidity: 83.6,
    precip: 0.008,
    precipprob: 38.7,
    precipcover: 4.17,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 19.5,
    windspeed: 16.6,
    winddir: 110,
    pressure: 1010.1,
    cloudcover: 25.3,
    visibility: 15,
    solarradiation: 286.9,
    solarenergy: 25,
    uvindex: 8,
    severerisk: 10,
    sunrise: '05:35:36',
    sunriseEpoch: 1714451736,
    sunset: '20:20:57',
    sunsetEpoch: 1714504857,
    moonphase: 0.73,
    conditions: 'Partially cloudy',
    description: 'Partly cloudy throughout the day.',
    icon: 'partly-cloudy-day',
    stations: null,
    source: 'fcst',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    datetime: '2024-05-01',
    datetimeEpoch: 1714518000,
    tempmax: 54.4,
    tempmin: 51.7,
    temp: 53,
    feelslikemax: 54.4,
    feelslikemin: 51.7,
    feelslike: 53,
    dew: 50,
    humidity: 89.6,
    precip: 0.008,
    precipprob: 48.4,
    precipcover: 8.33,
    preciptype: ['rain'],
    snow: 0,
    snowdepth: 0,
    windgust: 12.1,
    windspeed: 11.6,
    winddir: 176.8,
    pressure: 1010.2,
    cloudcover: 90.2,
    visibility: 14.8,
    solarradiation: 225,
    solarenergy: 19.6,
    uvindex: 7,
    severerisk: 10,
    sunrise: '05:33:46',
    sunriseEpoch: 1714538026,
    sunset: '20:22:33',
    sunsetEpoch: 1714591353,
    moonphase: 0.75,
    conditions: 'Rain, Overcast',
    description: 'Cloudy skies throughout the day with late afternoon rain.',
    icon: 'rain',
    stations: null,
    source: 'fcst',
    hours: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
];
export default days;
